/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxBenefitsRouteImport } from './routes/tax-benefits'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrepaymentRouteImport } from './routes/prepayment'
import { Route as PmayRouteImport } from './routes/pmay'
import { Route as EmiRouteImport } from './routes/emi'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as AffordabilityRouteImport } from './routes/affordability'
import { Route as IndexRouteImport } from './routes/index'

const TaxBenefitsRoute = TaxBenefitsRouteImport.update({
  id: '/tax-benefits',
  path: '/tax-benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepaymentRoute = PrepaymentRouteImport.update({
  id: '/prepayment',
  path: '/prepayment',
  getParentRoute: () => rootRouteImport,
} as any)
const PmayRoute = PmayRouteImport.update({
  id: '/pmay',
  path: '/pmay',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiRoute = EmiRouteImport.update({
  id: '/emi',
  path: '/emi',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const AffordabilityRoute = AffordabilityRouteImport.update({
  id: '/affordability',
  path: '/affordability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affordability': typeof AffordabilityRoute
  '/comparison': typeof ComparisonRoute
  '/emi': typeof EmiRoute
  '/pmay': typeof PmayRoute
  '/prepayment': typeof PrepaymentRoute
  '/privacy': typeof PrivacyRoute
  '/tax-benefits': typeof TaxBenefitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affordability': typeof AffordabilityRoute
  '/comparison': typeof ComparisonRoute
  '/emi': typeof EmiRoute
  '/pmay': typeof PmayRoute
  '/prepayment': typeof PrepaymentRoute
  '/privacy': typeof PrivacyRoute
  '/tax-benefits': typeof TaxBenefitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affordability': typeof AffordabilityRoute
  '/comparison': typeof ComparisonRoute
  '/emi': typeof EmiRoute
  '/pmay': typeof PmayRoute
  '/prepayment': typeof PrepaymentRoute
  '/privacy': typeof PrivacyRoute
  '/tax-benefits': typeof TaxBenefitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affordability'
    | '/comparison'
    | '/emi'
    | '/pmay'
    | '/prepayment'
    | '/privacy'
    | '/tax-benefits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affordability'
    | '/comparison'
    | '/emi'
    | '/pmay'
    | '/prepayment'
    | '/privacy'
    | '/tax-benefits'
  id:
    | '__root__'
    | '/'
    | '/affordability'
    | '/comparison'
    | '/emi'
    | '/pmay'
    | '/prepayment'
    | '/privacy'
    | '/tax-benefits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffordabilityRoute: typeof AffordabilityRoute
  ComparisonRoute: typeof ComparisonRoute
  EmiRoute: typeof EmiRoute
  PmayRoute: typeof PmayRoute
  PrepaymentRoute: typeof PrepaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  TaxBenefitsRoute: typeof TaxBenefitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tax-benefits': {
      id: '/tax-benefits'
      path: '/tax-benefits'
      fullPath: '/tax-benefits'
      preLoaderRoute: typeof TaxBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepayment': {
      id: '/prepayment'
      path: '/prepayment'
      fullPath: '/prepayment'
      preLoaderRoute: typeof PrepaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmay': {
      id: '/pmay'
      path: '/pmay'
      fullPath: '/pmay'
      preLoaderRoute: typeof PmayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi': {
      id: '/emi'
      path: '/emi'
      fullPath: '/emi'
      preLoaderRoute: typeof EmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affordability': {
      id: '/affordability'
      path: '/affordability'
      fullPath: '/affordability'
      preLoaderRoute: typeof AffordabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffordabilityRoute: AffordabilityRoute,
  ComparisonRoute: ComparisonRoute,
  EmiRoute: EmiRoute,
  PmayRoute: PmayRoute,
  PrepaymentRoute: PrepaymentRoute,
  PrivacyRoute: PrivacyRoute,
  TaxBenefitsRoute: TaxBenefitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
